/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

/**
 *
 * @author walte
 */
public class MapaDoJogo extends javax.swing.JFrame {

    /**
     * Creates new form MapaDoJogo
     */
    public MapaDoJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton34 = new javax.swing.JToggleButton();
        jToggleButton38 = new javax.swing.JToggleButton();
        jToggleButton50 = new javax.swing.JToggleButton();
        jToggleButton56 = new javax.swing.JToggleButton();
        jToggleButton62 = new javax.swing.JToggleButton();
        jToggleButton88 = new javax.swing.JToggleButton();
        jToggleButton61 = new javax.swing.JToggleButton();
        jToggleButton63 = new javax.swing.JToggleButton();
        jToggleButton72 = new javax.swing.JToggleButton();
        jToggleButton77 = new javax.swing.JToggleButton();
        jToggleButton78 = new javax.swing.JToggleButton();
        jToggleButton79 = new javax.swing.JToggleButton();
        jToggleButton80 = new javax.swing.JToggleButton();
        jToggleButton82 = new javax.swing.JToggleButton();
        jToggleButton83 = new javax.swing.JToggleButton();
        jToggleButton99 = new javax.swing.JToggleButton();
        jToggleButton110 = new javax.swing.JToggleButton();
        jToggleButton111 = new javax.swing.JToggleButton();
        jToggleButton112 = new javax.swing.JToggleButton();
        jToggleButton113 = new javax.swing.JToggleButton();
        jToggleButton114 = new javax.swing.JToggleButton();
        jToggleButton115 = new javax.swing.JToggleButton();
        jToggleButton116 = new javax.swing.JToggleButton();
        jToggleButton117 = new javax.swing.JToggleButton();
        jToggleButton118 = new javax.swing.JToggleButton();
        jToggleButton119 = new javax.swing.JToggleButton();
        jToggleButton120 = new javax.swing.JToggleButton();
        jToggleButton121 = new javax.swing.JToggleButton();
        jToggleButton122 = new javax.swing.JToggleButton();
        jToggleButton123 = new javax.swing.JToggleButton();
        jToggleButton124 = new javax.swing.JToggleButton();
        jToggleButton125 = new javax.swing.JToggleButton();
        jToggleButton126 = new javax.swing.JToggleButton();
        jToggleButton127 = new javax.swing.JToggleButton();
        jToggleButton128 = new javax.swing.JToggleButton();
        jToggleButton129 = new javax.swing.JToggleButton();
        jToggleButton130 = new javax.swing.JToggleButton();
        jToggleButton131 = new javax.swing.JToggleButton();
        jToggleButton132 = new javax.swing.JToggleButton();
        jToggleButton133 = new javax.swing.JToggleButton();
        jToggleButton134 = new javax.swing.JToggleButton();
        jToggleButton135 = new javax.swing.JToggleButton();
        jToggleButton136 = new javax.swing.JToggleButton();
        jToggleButton137 = new javax.swing.JToggleButton();
        jToggleButton138 = new javax.swing.JToggleButton();
        jToggleButton139 = new javax.swing.JToggleButton();
        jToggleButton140 = new javax.swing.JToggleButton();
        jToggleButton141 = new javax.swing.JToggleButton();
        jToggleButton142 = new javax.swing.JToggleButton();
        jToggleButton143 = new javax.swing.JToggleButton();
        jToggleButton144 = new javax.swing.JToggleButton();
        jToggleButton145 = new javax.swing.JToggleButton();
        jToggleButton146 = new javax.swing.JToggleButton();
        jToggleButton147 = new javax.swing.JToggleButton();
        jToggleButton148 = new javax.swing.JToggleButton();
        jToggleButton149 = new javax.swing.JToggleButton();
        jToggleButton150 = new javax.swing.JToggleButton();
        jToggleButton151 = new javax.swing.JToggleButton();
        jToggleButton152 = new javax.swing.JToggleButton();
        jToggleButton153 = new javax.swing.JToggleButton();
        jToggleButton154 = new javax.swing.JToggleButton();
        jToggleButton155 = new javax.swing.JToggleButton();
        jToggleButton156 = new javax.swing.JToggleButton();
        jToggleButton157 = new javax.swing.JToggleButton();
        jToggleButton158 = new javax.swing.JToggleButton();
        jToggleButton159 = new javax.swing.JToggleButton();
        jToggleButton160 = new javax.swing.JToggleButton();
        jToggleButton161 = new javax.swing.JToggleButton();
        jToggleButton162 = new javax.swing.JToggleButton();
        jToggleButton163 = new javax.swing.JToggleButton();
        jToggleButton164 = new javax.swing.JToggleButton();
        jToggleButton165 = new javax.swing.JToggleButton();
        jToggleButton166 = new javax.swing.JToggleButton();
        jToggleButton167 = new javax.swing.JToggleButton();
        jToggleButton168 = new javax.swing.JToggleButton();
        jToggleButton169 = new javax.swing.JToggleButton();
        jToggleButton170 = new javax.swing.JToggleButton();
        jToggleButton171 = new javax.swing.JToggleButton();
        jToggleButton172 = new javax.swing.JToggleButton();
        jToggleButton173 = new javax.swing.JToggleButton();
        jToggleButton174 = new javax.swing.JToggleButton();
        jToggleButton175 = new javax.swing.JToggleButton();
        jToggleButton176 = new javax.swing.JToggleButton();
        jToggleButton177 = new javax.swing.JToggleButton();
        jToggleButton178 = new javax.swing.JToggleButton();
        jToggleButton179 = new javax.swing.JToggleButton();
        jToggleButton180 = new javax.swing.JToggleButton();
        jToggleButton181 = new javax.swing.JToggleButton();
        jToggleButton182 = new javax.swing.JToggleButton();
        jToggleButton183 = new javax.swing.JToggleButton();
        jToggleButton184 = new javax.swing.JToggleButton();
        jToggleButton185 = new javax.swing.JToggleButton();
        jToggleButton186 = new javax.swing.JToggleButton();
        jToggleButton187 = new javax.swing.JToggleButton();
        jToggleButton188 = new javax.swing.JToggleButton();
        jToggleButton189 = new javax.swing.JToggleButton();
        jToggleButton190 = new javax.swing.JToggleButton();
        jToggleButton191 = new javax.swing.JToggleButton();
        jToggleButton192 = new javax.swing.JToggleButton();
        jToggleButton193 = new javax.swing.JToggleButton();
        jToggleButton194 = new javax.swing.JToggleButton();
        jToggleButton195 = new javax.swing.JToggleButton();
        jToggleButton196 = new javax.swing.JToggleButton();
        jToggleButton197 = new javax.swing.JToggleButton();
        jToggleButton198 = new javax.swing.JToggleButton();
        jToggleButton199 = new javax.swing.JToggleButton();
        jToggleButton200 = new javax.swing.JToggleButton();
        jToggleButton201 = new javax.swing.JToggleButton();
        jToggleButton202 = new javax.swing.JToggleButton();
        jToggleButton203 = new javax.swing.JToggleButton();
        jToggleButton204 = new javax.swing.JToggleButton();
        jToggleButton205 = new javax.swing.JToggleButton();
        jToggleButton206 = new javax.swing.JToggleButton();
        jToggleButton207 = new javax.swing.JToggleButton();
        jToggleButton208 = new javax.swing.JToggleButton();
        jToggleButton209 = new javax.swing.JToggleButton();
        jToggleButton210 = new javax.swing.JToggleButton();
        jToggleButton211 = new javax.swing.JToggleButton();
        jToggleButton212 = new javax.swing.JToggleButton();
        jToggleButton213 = new javax.swing.JToggleButton();
        jToggleButton214 = new javax.swing.JToggleButton();
        jToggleButton215 = new javax.swing.JToggleButton();
        jToggleButton216 = new javax.swing.JToggleButton();
        jToggleButton217 = new javax.swing.JToggleButton();
        jToggleButton218 = new javax.swing.JToggleButton();
        jToggleButton219 = new javax.swing.JToggleButton();
        jToggleButton220 = new javax.swing.JToggleButton();
        jToggleButton81 = new javax.swing.JToggleButton();
        jToggleButton84 = new javax.swing.JToggleButton();
        jToggleButton85 = new javax.swing.JToggleButton();
        jToggleButton221 = new javax.swing.JToggleButton();
        jToggleButton64 = new javax.swing.JToggleButton();
        jToggleButton65 = new javax.swing.JToggleButton();
        jToggleButton100 = new javax.swing.JToggleButton();
        jToggleButton73 = new javax.swing.JToggleButton();
        jToggleButton86 = new javax.swing.JToggleButton();
        jToggleButton87 = new javax.swing.JToggleButton();
        jToggleButton89 = new javax.swing.JToggleButton();

        jToggleButton13.setText("jToggleButton1");

        jToggleButton15.setText("jToggleButton1");

        jToggleButton34.setText("jToggleButton1");

        jToggleButton38.setText("jToggleButton1");

        jToggleButton50.setText("jToggleButton1");

        jToggleButton56.setText("jToggleButton1");

        jToggleButton62.setText("jToggleButton1");

        jToggleButton88.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 51));

        jToggleButton61.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton61.setText("jToggleButton1");

        jToggleButton63.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton63.setText("jToggleButton1");

        jToggleButton72.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton72.setText("jToggleButton1");

        jToggleButton77.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton77.setText("jToggleButton1");

        jToggleButton78.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton78.setText("jToggleButton1");

        jToggleButton79.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton79.setText("jToggleButton1");

        jToggleButton80.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton80.setText("jToggleButton1");

        jToggleButton82.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton82.setText("jToggleButton1");

        jToggleButton83.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton83.setText("jToggleButton1");

        jToggleButton99.setBackground(new java.awt.Color(153, 0, 51));
        jToggleButton99.setText("jToggleButton1");

        jToggleButton110.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton110.setText("jToggleButton1");

        jToggleButton111.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton111.setText("jToggleButton1");

        jToggleButton112.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton112.setText("jToggleButton1");

        jToggleButton113.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton113.setText("jToggleButton1");

        jToggleButton114.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton114.setText("jToggleButton1");

        jToggleButton115.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton115.setText("jToggleButton1");

        jToggleButton116.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton116.setText("jToggleButton1");

        jToggleButton117.setBackground(new java.awt.Color(153, 0, 51));
        jToggleButton117.setText("jToggleButton1");

        jToggleButton118.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton118.setText("jToggleButton1");

        jToggleButton119.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton119.setText("jToggleButton1");

        jToggleButton120.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton120.setText("jToggleButton1");

        jToggleButton121.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton121.setText("jToggleButton1");

        jToggleButton122.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton122.setText("jToggleButton1");

        jToggleButton123.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton123.setText("jToggleButton1");

        jToggleButton124.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton124.setText("jToggleButton1");

        jToggleButton125.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton125.setText("jToggleButton1");

        jToggleButton126.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton126.setText("jToggleButton1");

        jToggleButton127.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton127.setText("jToggleButton1");

        jToggleButton128.setBackground(new java.awt.Color(153, 0, 51));
        jToggleButton128.setText("jToggleButton1");

        jToggleButton129.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton129.setText("jToggleButton1");

        jToggleButton130.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton130.setText("jToggleButton1");

        jToggleButton131.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton131.setText("jToggleButton1");

        jToggleButton132.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton132.setText("jToggleButton1");

        jToggleButton133.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton133.setText("jToggleButton1");

        jToggleButton134.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton134.setText("jToggleButton1");

        jToggleButton135.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton135.setText("jToggleButton1");

        jToggleButton136.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton136.setText("jToggleButton1");

        jToggleButton137.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton137.setText("jToggleButton1");

        jToggleButton138.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton138.setText("jToggleButton1");

        jToggleButton139.setBackground(new java.awt.Color(153, 0, 51));
        jToggleButton139.setText("jToggleButton1");

        jToggleButton140.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton140.setText("jToggleButton1");

        jToggleButton141.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton141.setText("jToggleButton1");

        jToggleButton142.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton142.setText("jToggleButton1");

        jToggleButton143.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton143.setText("jToggleButton1");

        jToggleButton144.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton144.setText("jToggleButton1");

        jToggleButton145.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton145.setText("jToggleButton1");

        jToggleButton146.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton146.setText("jToggleButton1");

        jToggleButton147.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton147.setText("jToggleButton1");

        jToggleButton148.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton148.setText("jToggleButton1");

        jToggleButton149.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton149.setText("jToggleButton1");

        jToggleButton150.setBackground(new java.awt.Color(153, 0, 51));
        jToggleButton150.setText("jToggleButton1");

        jToggleButton151.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton151.setText("jToggleButton1");

        jToggleButton152.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton152.setText("jToggleButton1");

        jToggleButton153.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton153.setText("jToggleButton1");

        jToggleButton154.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton154.setText("jToggleButton1");

        jToggleButton155.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton155.setText("jToggleButton1");

        jToggleButton156.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton156.setText("jToggleButton1");

        jToggleButton157.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton157.setText("jToggleButton1");

        jToggleButton158.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton158.setText("jToggleButton1");

        jToggleButton159.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton159.setText("jToggleButton1");

        jToggleButton160.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton160.setText("jToggleButton1");

        jToggleButton161.setBackground(new java.awt.Color(153, 0, 51));
        jToggleButton161.setText("jToggleButton1");

        jToggleButton162.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton162.setText("jToggleButton1");

        jToggleButton163.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton163.setText("jToggleButton1");

        jToggleButton164.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton164.setText("jToggleButton1");

        jToggleButton165.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton165.setText("jToggleButton1");

        jToggleButton166.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton166.setText("jToggleButton1");

        jToggleButton167.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton167.setText("jToggleButton1");

        jToggleButton168.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton168.setText("jToggleButton1");

        jToggleButton169.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton169.setText("jToggleButton1");

        jToggleButton170.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton170.setText("jToggleButton1");

        jToggleButton171.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton171.setText("jToggleButton1");

        jToggleButton172.setBackground(new java.awt.Color(153, 0, 51));
        jToggleButton172.setText("jToggleButton1");

        jToggleButton173.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton173.setText("jToggleButton1");

        jToggleButton174.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton174.setText("jToggleButton1");

        jToggleButton175.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton175.setText("jToggleButton1");

        jToggleButton176.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton176.setText("jToggleButton1");

        jToggleButton177.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton177.setText("jToggleButton1");

        jToggleButton178.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton178.setText("jToggleButton1");

        jToggleButton179.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton179.setText("jToggleButton1");

        jToggleButton180.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton180.setText("jToggleButton1");

        jToggleButton181.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton181.setText("jToggleButton1");

        jToggleButton182.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton182.setText("jToggleButton1");

        jToggleButton183.setBackground(new java.awt.Color(153, 0, 51));
        jToggleButton183.setText("jToggleButton1");

        jToggleButton184.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton184.setText("jToggleButton1");

        jToggleButton185.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton185.setText("jToggleButton1");

        jToggleButton186.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton186.setText("jToggleButton1");

        jToggleButton187.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton187.setText("jToggleButton1");

        jToggleButton188.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton188.setText("jToggleButton1");

        jToggleButton189.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton189.setText("jToggleButton1");

        jToggleButton190.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton190.setText("jToggleButton1");

        jToggleButton191.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton191.setText("jToggleButton1");

        jToggleButton192.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton192.setText("jToggleButton1");

        jToggleButton193.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton193.setText("jToggleButton1");

        jToggleButton194.setBackground(new java.awt.Color(153, 0, 51));
        jToggleButton194.setText("jToggleButton1");

        jToggleButton195.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton195.setText("jToggleButton1");

        jToggleButton196.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton196.setText("jToggleButton1");

        jToggleButton197.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton197.setText("jToggleButton1");

        jToggleButton198.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton198.setText("jToggleButton1");

        jToggleButton199.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton199.setText("jToggleButton1");

        jToggleButton200.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton200.setText("jToggleButton1");

        jToggleButton201.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton201.setText("jToggleButton1");

        jToggleButton202.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton202.setText("jToggleButton1");

        jToggleButton203.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton203.setText("jToggleButton1");

        jToggleButton204.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton204.setText("jToggleButton1");

        jToggleButton205.setBackground(new java.awt.Color(153, 0, 51));
        jToggleButton205.setText("jToggleButton1");

        jToggleButton206.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton206.setText("jToggleButton1");

        jToggleButton207.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton207.setText("jToggleButton1");

        jToggleButton208.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton208.setText("jToggleButton1");

        jToggleButton209.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton209.setText("jToggleButton1");

        jToggleButton210.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton210.setText("jToggleButton1");

        jToggleButton211.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton211.setText("jToggleButton1");

        jToggleButton212.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton212.setText("jToggleButton1");

        jToggleButton213.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton213.setText("jToggleButton1");

        jToggleButton214.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton214.setText("jToggleButton1");

        jToggleButton215.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton215.setText("jToggleButton1");

        jToggleButton216.setBackground(new java.awt.Color(153, 0, 51));
        jToggleButton216.setText("jToggleButton1");

        jToggleButton217.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton217.setText("jToggleButton1");

        jToggleButton218.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton218.setText("jToggleButton1");

        jToggleButton219.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton219.setText("jToggleButton1");

        jToggleButton220.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton220.setText("jToggleButton1");

        jToggleButton81.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton81.setText("jToggleButton1");

        jToggleButton84.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton84.setText("jToggleButton1");

        jToggleButton85.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton85.setText("jToggleButton1");

        jToggleButton221.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton221.setText("jToggleButton1");

        jToggleButton64.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton64.setText("jToggleButton1");

        jToggleButton65.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton65.setText("jToggleButton1");

        jToggleButton100.setBackground(new java.awt.Color(153, 0, 51));
        jToggleButton100.setText("jToggleButton1");

        jToggleButton73.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton73.setText("jToggleButton1");

        jToggleButton86.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton86.setText("jToggleButton1");

        jToggleButton87.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton87.setText("jToggleButton1");

        jToggleButton89.setBackground(new java.awt.Color(153, 0, 0));
        jToggleButton89.setText("jToggleButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jToggleButton110, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton61, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton63, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton72, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton77, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton78, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton79, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton80, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton99, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton82, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton83, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jToggleButton114, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton115, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton116, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton118, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton119, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton120, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton121, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton111, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton117, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton112, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton113, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton125, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton126, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton127, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton129, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton130, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton131, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton132, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton122, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton128, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton123, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton124, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton136, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton137, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton138, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton140, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton141, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton142, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton143, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton133, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton139, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton134, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton135, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton147, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton148, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton149, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton151, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton152, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton153, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton154, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton144, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton150, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton145, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton146, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton158, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton159, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton160, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton162, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton163, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton164, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton165, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton155, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton161, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton156, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton157, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton169, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton170, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton171, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton173, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton174, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton175, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton176, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton166, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton172, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton167, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton168, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton180, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton181, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton182, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton184, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton185, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton186, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton187, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton177, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton183, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton178, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton179, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton191, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton192, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton193, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton195, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton196, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton197, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton198, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton188, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton194, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton189, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton190, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton202, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton203, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton204, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton206, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton207, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton208, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton209, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton199, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton205, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton200, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton201, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton213, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton214, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton215, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton217, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton218, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton219, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton220, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton210, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton216, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton211, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton212, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton221, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton64, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton65, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton73, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton86, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton87, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton89, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton81, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton100, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton84, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton85, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton61, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton110, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton63, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton72, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton77, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton78, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton79, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton80, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton99, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton82, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton83, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton64, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton221, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton65, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton73, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton86, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton87, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton89, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton81, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton100, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton84, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton85, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton214, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton213, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton215, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton217, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton218, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton219, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton220, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton210, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton216, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton211, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton212, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton203, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton202, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton204, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton206, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton207, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton208, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton209, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton199, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton205, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton200, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton201, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton192, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton191, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton193, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton195, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton196, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton197, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton198, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton188, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton194, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton189, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton190, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton181, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton180, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton182, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton184, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton185, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton186, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton187, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton177, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton183, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton178, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton179, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton170, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton169, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton171, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton173, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton174, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton175, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton176, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton166, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton172, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton167, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton168, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton159, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton158, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton160, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton162, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton163, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton164, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton165, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton155, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton161, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton156, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton157, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton148, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton147, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton149, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton151, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton152, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton153, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton154, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton144, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton150, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton145, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton146, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton137, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton136, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton138, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton140, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton141, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton142, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton143, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton133, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton139, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton134, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton135, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton126, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton125, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton127, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton129, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton130, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton131, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton132, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton122, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton128, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton123, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton124, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton115, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton114, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton116, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton118, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton119, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton120, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton121, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton111, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton117, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton112, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton113, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapaDoJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton100;
    private javax.swing.JToggleButton jToggleButton110;
    private javax.swing.JToggleButton jToggleButton111;
    private javax.swing.JToggleButton jToggleButton112;
    private javax.swing.JToggleButton jToggleButton113;
    private javax.swing.JToggleButton jToggleButton114;
    private javax.swing.JToggleButton jToggleButton115;
    private javax.swing.JToggleButton jToggleButton116;
    private javax.swing.JToggleButton jToggleButton117;
    private javax.swing.JToggleButton jToggleButton118;
    private javax.swing.JToggleButton jToggleButton119;
    private javax.swing.JToggleButton jToggleButton120;
    private javax.swing.JToggleButton jToggleButton121;
    private javax.swing.JToggleButton jToggleButton122;
    private javax.swing.JToggleButton jToggleButton123;
    private javax.swing.JToggleButton jToggleButton124;
    private javax.swing.JToggleButton jToggleButton125;
    private javax.swing.JToggleButton jToggleButton126;
    private javax.swing.JToggleButton jToggleButton127;
    private javax.swing.JToggleButton jToggleButton128;
    private javax.swing.JToggleButton jToggleButton129;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton130;
    private javax.swing.JToggleButton jToggleButton131;
    private javax.swing.JToggleButton jToggleButton132;
    private javax.swing.JToggleButton jToggleButton133;
    private javax.swing.JToggleButton jToggleButton134;
    private javax.swing.JToggleButton jToggleButton135;
    private javax.swing.JToggleButton jToggleButton136;
    private javax.swing.JToggleButton jToggleButton137;
    private javax.swing.JToggleButton jToggleButton138;
    private javax.swing.JToggleButton jToggleButton139;
    private javax.swing.JToggleButton jToggleButton140;
    private javax.swing.JToggleButton jToggleButton141;
    private javax.swing.JToggleButton jToggleButton142;
    private javax.swing.JToggleButton jToggleButton143;
    private javax.swing.JToggleButton jToggleButton144;
    private javax.swing.JToggleButton jToggleButton145;
    private javax.swing.JToggleButton jToggleButton146;
    private javax.swing.JToggleButton jToggleButton147;
    private javax.swing.JToggleButton jToggleButton148;
    private javax.swing.JToggleButton jToggleButton149;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton150;
    private javax.swing.JToggleButton jToggleButton151;
    private javax.swing.JToggleButton jToggleButton152;
    private javax.swing.JToggleButton jToggleButton153;
    private javax.swing.JToggleButton jToggleButton154;
    private javax.swing.JToggleButton jToggleButton155;
    private javax.swing.JToggleButton jToggleButton156;
    private javax.swing.JToggleButton jToggleButton157;
    private javax.swing.JToggleButton jToggleButton158;
    private javax.swing.JToggleButton jToggleButton159;
    private javax.swing.JToggleButton jToggleButton160;
    private javax.swing.JToggleButton jToggleButton161;
    private javax.swing.JToggleButton jToggleButton162;
    private javax.swing.JToggleButton jToggleButton163;
    private javax.swing.JToggleButton jToggleButton164;
    private javax.swing.JToggleButton jToggleButton165;
    private javax.swing.JToggleButton jToggleButton166;
    private javax.swing.JToggleButton jToggleButton167;
    private javax.swing.JToggleButton jToggleButton168;
    private javax.swing.JToggleButton jToggleButton169;
    private javax.swing.JToggleButton jToggleButton170;
    private javax.swing.JToggleButton jToggleButton171;
    private javax.swing.JToggleButton jToggleButton172;
    private javax.swing.JToggleButton jToggleButton173;
    private javax.swing.JToggleButton jToggleButton174;
    private javax.swing.JToggleButton jToggleButton175;
    private javax.swing.JToggleButton jToggleButton176;
    private javax.swing.JToggleButton jToggleButton177;
    private javax.swing.JToggleButton jToggleButton178;
    private javax.swing.JToggleButton jToggleButton179;
    private javax.swing.JToggleButton jToggleButton180;
    private javax.swing.JToggleButton jToggleButton181;
    private javax.swing.JToggleButton jToggleButton182;
    private javax.swing.JToggleButton jToggleButton183;
    private javax.swing.JToggleButton jToggleButton184;
    private javax.swing.JToggleButton jToggleButton185;
    private javax.swing.JToggleButton jToggleButton186;
    private javax.swing.JToggleButton jToggleButton187;
    private javax.swing.JToggleButton jToggleButton188;
    private javax.swing.JToggleButton jToggleButton189;
    private javax.swing.JToggleButton jToggleButton190;
    private javax.swing.JToggleButton jToggleButton191;
    private javax.swing.JToggleButton jToggleButton192;
    private javax.swing.JToggleButton jToggleButton193;
    private javax.swing.JToggleButton jToggleButton194;
    private javax.swing.JToggleButton jToggleButton195;
    private javax.swing.JToggleButton jToggleButton196;
    private javax.swing.JToggleButton jToggleButton197;
    private javax.swing.JToggleButton jToggleButton198;
    private javax.swing.JToggleButton jToggleButton199;
    private javax.swing.JToggleButton jToggleButton200;
    private javax.swing.JToggleButton jToggleButton201;
    private javax.swing.JToggleButton jToggleButton202;
    private javax.swing.JToggleButton jToggleButton203;
    private javax.swing.JToggleButton jToggleButton204;
    private javax.swing.JToggleButton jToggleButton205;
    private javax.swing.JToggleButton jToggleButton206;
    private javax.swing.JToggleButton jToggleButton207;
    private javax.swing.JToggleButton jToggleButton208;
    private javax.swing.JToggleButton jToggleButton209;
    private javax.swing.JToggleButton jToggleButton210;
    private javax.swing.JToggleButton jToggleButton211;
    private javax.swing.JToggleButton jToggleButton212;
    private javax.swing.JToggleButton jToggleButton213;
    private javax.swing.JToggleButton jToggleButton214;
    private javax.swing.JToggleButton jToggleButton215;
    private javax.swing.JToggleButton jToggleButton216;
    private javax.swing.JToggleButton jToggleButton217;
    private javax.swing.JToggleButton jToggleButton218;
    private javax.swing.JToggleButton jToggleButton219;
    private javax.swing.JToggleButton jToggleButton220;
    private javax.swing.JToggleButton jToggleButton221;
    private javax.swing.JToggleButton jToggleButton34;
    private javax.swing.JToggleButton jToggleButton38;
    private javax.swing.JToggleButton jToggleButton50;
    private javax.swing.JToggleButton jToggleButton56;
    private javax.swing.JToggleButton jToggleButton61;
    private javax.swing.JToggleButton jToggleButton62;
    private javax.swing.JToggleButton jToggleButton63;
    private javax.swing.JToggleButton jToggleButton64;
    private javax.swing.JToggleButton jToggleButton65;
    private javax.swing.JToggleButton jToggleButton72;
    private javax.swing.JToggleButton jToggleButton73;
    private javax.swing.JToggleButton jToggleButton77;
    private javax.swing.JToggleButton jToggleButton78;
    private javax.swing.JToggleButton jToggleButton79;
    private javax.swing.JToggleButton jToggleButton80;
    private javax.swing.JToggleButton jToggleButton81;
    private javax.swing.JToggleButton jToggleButton82;
    private javax.swing.JToggleButton jToggleButton83;
    private javax.swing.JToggleButton jToggleButton84;
    private javax.swing.JToggleButton jToggleButton85;
    private javax.swing.JToggleButton jToggleButton86;
    private javax.swing.JToggleButton jToggleButton87;
    private javax.swing.JToggleButton jToggleButton88;
    private javax.swing.JToggleButton jToggleButton89;
    private javax.swing.JToggleButton jToggleButton99;
    // End of variables declaration//GEN-END:variables
}
