/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author walte
 */
public class MapaDoJogo extends javax.swing.JFrame {

    /**
     * Creates new form MapaDoJogo
     */
    public MapaDoJogo() {
        initComponents();
    }
    public static int cont=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton34 = new javax.swing.JToggleButton();
        jToggleButton38 = new javax.swing.JToggleButton();
        jToggleButton50 = new javax.swing.JToggleButton();
        jToggleButton56 = new javax.swing.JToggleButton();
        jToggleButton62 = new javax.swing.JToggleButton();
        jToggleButton88 = new javax.swing.JToggleButton();
        jbtn1x2 = new javax.swing.JToggleButton();
        jbtn1x3 = new javax.swing.JToggleButton();
        jbtn1x4 = new javax.swing.JToggleButton();
        jbtn1x5 = new javax.swing.JToggleButton();
        jbtn1x6 = new javax.swing.JToggleButton();
        jbtn1x7 = new javax.swing.JToggleButton();
        jbtn1x8 = new javax.swing.JToggleButton();
        jbtn1x1 = new javax.swing.JToggleButton();
        jbtn8x8 = new javax.swing.JToggleButton();
        jbtn8x1 = new javax.swing.JToggleButton();
        jbtn8x2 = new javax.swing.JToggleButton();
        jbtn8x3 = new javax.swing.JToggleButton();
        jbtn8x4 = new javax.swing.JToggleButton();
        jbtn8x5 = new javax.swing.JToggleButton();
        jbtn8x6 = new javax.swing.JToggleButton();
        jbtn8x7 = new javax.swing.JToggleButton();
        jbtn7x8 = new javax.swing.JToggleButton();
        jbtn7x1 = new javax.swing.JToggleButton();
        jbtn7x2 = new javax.swing.JToggleButton();
        jbtn7x3 = new javax.swing.JToggleButton();
        jbtn7x4 = new javax.swing.JToggleButton();
        jbtn7x5 = new javax.swing.JToggleButton();
        jbtn7x6 = new javax.swing.JToggleButton();
        jbtn7x7 = new javax.swing.JToggleButton();
        jbtn6x8 = new javax.swing.JToggleButton();
        jbtn6x1 = new javax.swing.JToggleButton();
        jbtn6x2 = new javax.swing.JToggleButton();
        jbtn6x3 = new javax.swing.JToggleButton();
        jbtn6x4 = new javax.swing.JToggleButton();
        jbtn6x5 = new javax.swing.JToggleButton();
        jbtn6x6 = new javax.swing.JToggleButton();
        jbtn6x7 = new javax.swing.JToggleButton();
        jbtn5x8 = new javax.swing.JToggleButton();
        jbtn5x1 = new javax.swing.JToggleButton();
        jbtn5x2 = new javax.swing.JToggleButton();
        jbtn5x3 = new javax.swing.JToggleButton();
        jbtn5x4 = new javax.swing.JToggleButton();
        jbtn5x5 = new javax.swing.JToggleButton();
        jbtn5x6 = new javax.swing.JToggleButton();
        jbtn5x7 = new javax.swing.JToggleButton();
        jbtn4x8 = new javax.swing.JToggleButton();
        jbtn4x1 = new javax.swing.JToggleButton();
        jbtn4x2 = new javax.swing.JToggleButton();
        jbtn4x3 = new javax.swing.JToggleButton();
        jbtn4x4 = new javax.swing.JToggleButton();
        jbtn4x5 = new javax.swing.JToggleButton();
        jbtn4x6 = new javax.swing.JToggleButton();
        jbtn4x7 = new javax.swing.JToggleButton();
        jbtn3x8 = new javax.swing.JToggleButton();
        jbtn3x1 = new javax.swing.JToggleButton();
        jbtn3x2 = new javax.swing.JToggleButton();
        jbtn3x3 = new javax.swing.JToggleButton();
        jbtn3x4 = new javax.swing.JToggleButton();
        jbtn3x5 = new javax.swing.JToggleButton();
        jbtn3x6 = new javax.swing.JToggleButton();
        jbtn3x7 = new javax.swing.JToggleButton();
        jbtn2x8 = new javax.swing.JToggleButton();
        jbtn2x1 = new javax.swing.JToggleButton();
        jbtn2x2 = new javax.swing.JToggleButton();
        jbtn2x3 = new javax.swing.JToggleButton();
        jbtn2x4 = new javax.swing.JToggleButton();
        jbtn2x5 = new javax.swing.JToggleButton();
        jbtn2x6 = new javax.swing.JToggleButton();
        jbtn2x7 = new javax.swing.JToggleButton();

        jToggleButton13.setText("jToggleButton1");

        jToggleButton15.setText("jToggleButton1");

        jToggleButton34.setText("jToggleButton1");

        jToggleButton38.setText("jToggleButton1");

        jToggleButton50.setText("jToggleButton1");

        jToggleButton56.setText("jToggleButton1");

        jToggleButton62.setText("jToggleButton1");

        jToggleButton88.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 51));

        jbtn1x2.setBackground(new java.awt.Color(153, 0, 0));
        jbtn1x2.setText("?");
        jbtn1x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1x2ActionPerformed(evt);
            }
        });

        jbtn1x3.setBackground(new java.awt.Color(153, 0, 0));
        jbtn1x3.setText("?");
        jbtn1x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1x3ActionPerformed(evt);
            }
        });

        jbtn1x4.setBackground(new java.awt.Color(153, 0, 0));
        jbtn1x4.setText("?");
        jbtn1x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1x4ActionPerformed(evt);
            }
        });

        jbtn1x5.setBackground(new java.awt.Color(153, 0, 0));
        jbtn1x5.setText("?");
        jbtn1x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1x5ActionPerformed(evt);
            }
        });

        jbtn1x6.setBackground(new java.awt.Color(153, 0, 0));
        jbtn1x6.setText("?");
        jbtn1x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1x6ActionPerformed(evt);
            }
        });

        jbtn1x7.setBackground(new java.awt.Color(153, 0, 0));
        jbtn1x7.setText("?");
        jbtn1x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1x7ActionPerformed(evt);
            }
        });

        jbtn1x8.setBackground(new java.awt.Color(153, 0, 0));
        jbtn1x8.setText("?");
        jbtn1x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1x8ActionPerformed(evt);
            }
        });

        jbtn1x1.setBackground(new java.awt.Color(153, 0, 0));
        jbtn1x1.setText("?");
        jbtn1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1x1ActionPerformed(evt);
            }
        });

        jbtn8x8.setBackground(new java.awt.Color(153, 0, 0));
        jbtn8x8.setText("?");
        jbtn8x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8x8ActionPerformed(evt);
            }
        });

        jbtn8x1.setBackground(new java.awt.Color(153, 0, 0));
        jbtn8x1.setText("?");
        jbtn8x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8x1ActionPerformed(evt);
            }
        });

        jbtn8x2.setBackground(new java.awt.Color(153, 0, 0));
        jbtn8x2.setText("?");
        jbtn8x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8x2ActionPerformed(evt);
            }
        });

        jbtn8x3.setBackground(new java.awt.Color(153, 0, 0));
        jbtn8x3.setText("?");
        jbtn8x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8x3ActionPerformed(evt);
            }
        });

        jbtn8x4.setBackground(new java.awt.Color(153, 0, 0));
        jbtn8x4.setText("?");
        jbtn8x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8x4ActionPerformed(evt);
            }
        });

        jbtn8x5.setBackground(new java.awt.Color(153, 0, 0));
        jbtn8x5.setText("?");
        jbtn8x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8x5ActionPerformed(evt);
            }
        });

        jbtn8x6.setBackground(new java.awt.Color(153, 0, 0));
        jbtn8x6.setText("?");
        jbtn8x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8x6ActionPerformed(evt);
            }
        });

        jbtn8x7.setBackground(new java.awt.Color(153, 0, 0));
        jbtn8x7.setText("?");
        jbtn8x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8x7ActionPerformed(evt);
            }
        });

        jbtn7x8.setBackground(new java.awt.Color(153, 0, 0));
        jbtn7x8.setText("?");
        jbtn7x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7x8ActionPerformed(evt);
            }
        });

        jbtn7x1.setBackground(new java.awt.Color(153, 0, 0));
        jbtn7x1.setText("?");
        jbtn7x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7x1ActionPerformed(evt);
            }
        });

        jbtn7x2.setBackground(new java.awt.Color(153, 0, 0));
        jbtn7x2.setText("?");
        jbtn7x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7x2ActionPerformed(evt);
            }
        });

        jbtn7x3.setBackground(new java.awt.Color(153, 0, 0));
        jbtn7x3.setText("?");
        jbtn7x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7x3ActionPerformed(evt);
            }
        });

        jbtn7x4.setBackground(new java.awt.Color(153, 0, 0));
        jbtn7x4.setText("?");
        jbtn7x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7x4ActionPerformed(evt);
            }
        });

        jbtn7x5.setBackground(new java.awt.Color(153, 0, 0));
        jbtn7x5.setText("?");
        jbtn7x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7x5ActionPerformed(evt);
            }
        });

        jbtn7x6.setBackground(new java.awt.Color(153, 0, 0));
        jbtn7x6.setText("?");
        jbtn7x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7x6ActionPerformed(evt);
            }
        });

        jbtn7x7.setBackground(new java.awt.Color(153, 0, 0));
        jbtn7x7.setText("?");
        jbtn7x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7x7ActionPerformed(evt);
            }
        });

        jbtn6x8.setBackground(new java.awt.Color(153, 0, 0));
        jbtn6x8.setText("?");
        jbtn6x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6x8ActionPerformed(evt);
            }
        });

        jbtn6x1.setBackground(new java.awt.Color(153, 0, 0));
        jbtn6x1.setText("?");
        jbtn6x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6x1ActionPerformed(evt);
            }
        });

        jbtn6x2.setBackground(new java.awt.Color(153, 0, 0));
        jbtn6x2.setText("?");
        jbtn6x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6x2ActionPerformed(evt);
            }
        });

        jbtn6x3.setBackground(new java.awt.Color(153, 0, 0));
        jbtn6x3.setText("?");
        jbtn6x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6x3ActionPerformed(evt);
            }
        });

        jbtn6x4.setBackground(new java.awt.Color(153, 0, 0));
        jbtn6x4.setText("?");
        jbtn6x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6x4ActionPerformed(evt);
            }
        });

        jbtn6x5.setBackground(new java.awt.Color(153, 0, 0));
        jbtn6x5.setText("?");
        jbtn6x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6x5ActionPerformed(evt);
            }
        });

        jbtn6x6.setBackground(new java.awt.Color(153, 0, 0));
        jbtn6x6.setText("?");
        jbtn6x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6x6ActionPerformed(evt);
            }
        });

        jbtn6x7.setBackground(new java.awt.Color(153, 0, 0));
        jbtn6x7.setText("?");
        jbtn6x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6x7ActionPerformed(evt);
            }
        });

        jbtn5x8.setBackground(new java.awt.Color(153, 0, 0));
        jbtn5x8.setText("?");
        jbtn5x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5x8ActionPerformed(evt);
            }
        });

        jbtn5x1.setBackground(new java.awt.Color(153, 0, 0));
        jbtn5x1.setText("?");
        jbtn5x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5x1ActionPerformed(evt);
            }
        });

        jbtn5x2.setBackground(new java.awt.Color(153, 0, 0));
        jbtn5x2.setText("?");
        jbtn5x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5x2ActionPerformed(evt);
            }
        });

        jbtn5x3.setBackground(new java.awt.Color(153, 0, 0));
        jbtn5x3.setText("?");
        jbtn5x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5x3ActionPerformed(evt);
            }
        });

        jbtn5x4.setBackground(new java.awt.Color(153, 0, 0));
        jbtn5x4.setText("?");
        jbtn5x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5x4ActionPerformed(evt);
            }
        });

        jbtn5x5.setBackground(new java.awt.Color(153, 0, 0));
        jbtn5x5.setText("?");
        jbtn5x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5x5ActionPerformed(evt);
            }
        });

        jbtn5x6.setBackground(new java.awt.Color(153, 0, 0));
        jbtn5x6.setText("?");
        jbtn5x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5x6ActionPerformed(evt);
            }
        });

        jbtn5x7.setBackground(new java.awt.Color(153, 0, 0));
        jbtn5x7.setText("?");
        jbtn5x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5x7ActionPerformed(evt);
            }
        });

        jbtn4x8.setBackground(new java.awt.Color(153, 0, 0));
        jbtn4x8.setText("?");
        jbtn4x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4x8ActionPerformed(evt);
            }
        });

        jbtn4x1.setBackground(new java.awt.Color(153, 0, 0));
        jbtn4x1.setText("?");
        jbtn4x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4x1ActionPerformed(evt);
            }
        });

        jbtn4x2.setBackground(new java.awt.Color(153, 0, 0));
        jbtn4x2.setText("?");
        jbtn4x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4x2ActionPerformed(evt);
            }
        });

        jbtn4x3.setBackground(new java.awt.Color(153, 0, 0));
        jbtn4x3.setText("?");
        jbtn4x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4x3ActionPerformed(evt);
            }
        });

        jbtn4x4.setBackground(new java.awt.Color(153, 0, 0));
        jbtn4x4.setText("?");
        jbtn4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4x4ActionPerformed(evt);
            }
        });

        jbtn4x5.setBackground(new java.awt.Color(153, 0, 0));
        jbtn4x5.setText("?");
        jbtn4x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4x5ActionPerformed(evt);
            }
        });

        jbtn4x6.setBackground(new java.awt.Color(153, 0, 0));
        jbtn4x6.setText("?");
        jbtn4x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4x6ActionPerformed(evt);
            }
        });

        jbtn4x7.setBackground(new java.awt.Color(153, 0, 0));
        jbtn4x7.setText("?");
        jbtn4x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4x7ActionPerformed(evt);
            }
        });

        jbtn3x8.setBackground(new java.awt.Color(153, 0, 0));
        jbtn3x8.setText("?");
        jbtn3x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3x8ActionPerformed(evt);
            }
        });

        jbtn3x1.setBackground(new java.awt.Color(153, 0, 0));
        jbtn3x1.setText("?");
        jbtn3x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3x1ActionPerformed(evt);
            }
        });

        jbtn3x2.setBackground(new java.awt.Color(153, 0, 0));
        jbtn3x2.setText("?");
        jbtn3x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3x2ActionPerformed(evt);
            }
        });

        jbtn3x3.setBackground(new java.awt.Color(153, 0, 0));
        jbtn3x3.setText("?");
        jbtn3x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3x3ActionPerformed(evt);
            }
        });

        jbtn3x4.setBackground(new java.awt.Color(153, 0, 0));
        jbtn3x4.setText("?");
        jbtn3x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3x4ActionPerformed(evt);
            }
        });

        jbtn3x5.setBackground(new java.awt.Color(153, 0, 0));
        jbtn3x5.setText("?");
        jbtn3x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3x5ActionPerformed(evt);
            }
        });

        jbtn3x6.setBackground(new java.awt.Color(153, 0, 0));
        jbtn3x6.setText("?");
        jbtn3x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3x6ActionPerformed(evt);
            }
        });

        jbtn3x7.setBackground(new java.awt.Color(153, 0, 0));
        jbtn3x7.setText("?");
        jbtn3x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3x7ActionPerformed(evt);
            }
        });

        jbtn2x8.setBackground(new java.awt.Color(153, 0, 0));
        jbtn2x8.setText("?");
        jbtn2x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2x8ActionPerformed(evt);
            }
        });

        jbtn2x1.setBackground(new java.awt.Color(153, 0, 0));
        jbtn2x1.setText("?");
        jbtn2x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2x1ActionPerformed(evt);
            }
        });

        jbtn2x2.setBackground(new java.awt.Color(153, 0, 0));
        jbtn2x2.setText("?");
        jbtn2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2x2ActionPerformed(evt);
            }
        });

        jbtn2x3.setBackground(new java.awt.Color(153, 0, 0));
        jbtn2x3.setText("?");
        jbtn2x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2x3ActionPerformed(evt);
            }
        });

        jbtn2x4.setBackground(new java.awt.Color(153, 0, 0));
        jbtn2x4.setText("?");
        jbtn2x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2x4ActionPerformed(evt);
            }
        });

        jbtn2x5.setBackground(new java.awt.Color(153, 0, 0));
        jbtn2x5.setText("?");
        jbtn2x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2x5ActionPerformed(evt);
            }
        });

        jbtn2x6.setBackground(new java.awt.Color(153, 0, 0));
        jbtn2x6.setText("?");
        jbtn2x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2x6ActionPerformed(evt);
            }
        });

        jbtn2x7.setBackground(new java.awt.Color(153, 0, 0));
        jbtn2x7.setText("?");
        jbtn2x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2x7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtn1x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn1x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn1x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn1x4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn1x5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn1x6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn1x7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn1x8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn8x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn8x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn8x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn8x4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn8x5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn8x6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn8x7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn8x8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn7x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn7x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn7x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn7x4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn7x5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn7x6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn7x7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn7x8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn6x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn6x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn6x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn6x4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn6x5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn6x6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn6x7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn6x8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn5x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn5x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn5x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn5x4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn5x5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn5x6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn5x7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn5x8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn4x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn4x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn4x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn4x4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn4x5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn4x6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn4x7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn4x8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn3x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn3x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn3x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn3x4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn3x5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn3x6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn3x7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn3x8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn2x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn2x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn2x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn2x4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn2x5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn2x6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn2x7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbtn2x8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn1x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn1x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn1x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn1x4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn1x5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn1x6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn1x7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn1x8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn2x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn2x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtn2x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn2x4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn2x5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn2x6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn2x7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn2x8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn3x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn3x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtn3x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn3x4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn3x5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn3x6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn3x7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn3x8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn4x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn4x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtn4x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn4x4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn4x5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn4x6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn4x7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn4x8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn5x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn5x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtn5x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn5x4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn5x5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn5x6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn5x7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn5x8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn6x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn6x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtn6x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn6x4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn6x5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn6x6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn6x7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn6x8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn7x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn7x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtn7x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn7x4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn7x5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn7x6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn7x7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn7x8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn8x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn8x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtn8x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn8x4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn8x5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn8x6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn8x7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn8x8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1x1ActionPerformed
        
        jbtn1x1.setText("*");//1
        JOptionPane.showMessageDialog(null, "BOOM!");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn1x1ActionPerformed

    private void jbtn3x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3x3ActionPerformed
        jbtn3x3.setText("*");//2
        JOptionPane.showMessageDialog(null, "BOOM!");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn3x3ActionPerformed

    private void jbtn2x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2x7ActionPerformed

        jbtn2x7.setText("*");//3
        JOptionPane.showMessageDialog(null, "BOOM!");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn2x7ActionPerformed

    private void jbtn8x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8x6ActionPerformed
        jbtn8x6.setText("*");//4
        JOptionPane.showMessageDialog(null, "BOOM!");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn8x6ActionPerformed

    private void jbtn7x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7x2ActionPerformed
        jbtn7x2.setText("*");//5
        JOptionPane.showMessageDialog(null, "BOOM!");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn7x2ActionPerformed

    private void jbtn6x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6x6ActionPerformed
        jbtn6x6.setText("*");//6
        JOptionPane.showMessageDialog(null, "BOOM!");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn6x6ActionPerformed

    private void jbtn5x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5x4ActionPerformed
        jbtn5x4.setText("*");//7
        JOptionPane.showMessageDialog(null, "BOOM!");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn5x4ActionPerformed

    private void jbtn4x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4x5ActionPerformed
        jbtn4x5.setText("*");//8
        JOptionPane.showMessageDialog(null, "BOOM!");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn4x5ActionPerformed

    private void jbtn3x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3x2ActionPerformed
        jbtn3x2.setText("*");//9
        JOptionPane.showMessageDialog(null, "BOOM!");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn3x2ActionPerformed

    private void jbtn2x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2x5ActionPerformed
        jbtn2x5.setText("*");//10
        JOptionPane.showMessageDialog(null, "BOOM!");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn2x5ActionPerformed

    private void jbtn4x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4x6ActionPerformed
        jbtn4x6.setText("*");//11
        JOptionPane.showMessageDialog(null, "BOOM!");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn4x6ActionPerformed

    private void jbtn5x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5x1ActionPerformed
        jbtn5x1.setText("*");//12
        JOptionPane.showMessageDialog(null, "BOOM!");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn5x1ActionPerformed

    private void jbtn3x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3x7ActionPerformed
        jbtn3x7.setText("*");//13
        JOptionPane.showMessageDialog(null, "BOOM!");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn3x7ActionPerformed

    private void jbtn2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2x2ActionPerformed
        jbtn2x2.setText("*");//14
        JOptionPane.showMessageDialog(null, "BOOM!");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn2x2ActionPerformed

    private void jbtn6x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6x8ActionPerformed
        jbtn6x8.setText("*");//15
        JOptionPane.showMessageDialog(null, "BOOM!");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jbtn6x8ActionPerformed

    private void jbtn2x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2x3ActionPerformed
        jbtn2x3.setText("*");//16
        JOptionPane.showMessageDialog(null, "BOOM!");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn2x3ActionPerformed

    private void jbtn1x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1x2ActionPerformed
        jbtn1x2.setText("2");//1
        cont++;
        jbtn1x2.setEnabled(false);
        
    }//GEN-LAST:event_jbtn1x2ActionPerformed

    private void jbtn1x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1x3ActionPerformed
        jbtn1x3.setText("3");//1
        cont++;
        jbtn1x3.setEnabled(false);
    }//GEN-LAST:event_jbtn1x3ActionPerformed

    private void jbtn1x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1x4ActionPerformed
        jbtn1x4.setText("4");//1
        cont++;
        jbtn1x4.setEnabled(false);
    }//GEN-LAST:event_jbtn1x4ActionPerformed

    private void jbtn1x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1x5ActionPerformed
        jbtn1x5.setText("5");//1
        cont++;
        jbtn1x5.setEnabled(false);
    }//GEN-LAST:event_jbtn1x5ActionPerformed

    private void jbtn1x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1x6ActionPerformed
        jbtn1x6.setText("6");//1
        cont++;
        jbtn1x6.setEnabled(false);
    }//GEN-LAST:event_jbtn1x6ActionPerformed

    private void jbtn1x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1x7ActionPerformed
        jbtn1x1.setText("7");//1
        cont++;
        jbtn1x7.setEnabled(false);
    }//GEN-LAST:event_jbtn1x7ActionPerformed

    private void jbtn1x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1x8ActionPerformed
        jbtn1x8.setText("8");//1
        cont++;
        jbtn1x8.setEnabled(false);
    }//GEN-LAST:event_jbtn1x8ActionPerformed

    private void jbtn2x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2x1ActionPerformed
        jbtn2x1.setText("1");//1
        cont++;
        jbtn2x1.setEnabled(false);
    }//GEN-LAST:event_jbtn2x1ActionPerformed

    private void jbtn2x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2x4ActionPerformed
        jbtn2x4.setText("2");//1
        cont++;
        jbtn2x4.setEnabled(false);
    }//GEN-LAST:event_jbtn2x4ActionPerformed

    private void jbtn2x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2x6ActionPerformed
        jbtn2x6.setText("3");
        cont++;
        jbtn2x6.setEnabled(false);
    }//GEN-LAST:event_jbtn2x6ActionPerformed

    private void jbtn2x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2x8ActionPerformed
       jbtn2x8.setText("4");
        cont++;
        jbtn2x8.setEnabled(false);
    }//GEN-LAST:event_jbtn2x8ActionPerformed

    private void jbtn3x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3x1ActionPerformed
        jbtn3x1.setText("5");
        cont++;
        jbtn3x1.setEnabled(false);
    }//GEN-LAST:event_jbtn3x1ActionPerformed

    private void jbtn3x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3x4ActionPerformed
        jbtn3x4.setText("6");
        cont++;
        jbtn3x4.setEnabled(false);
    }//GEN-LAST:event_jbtn3x4ActionPerformed

    private void jbtn3x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3x5ActionPerformed
        jbtn3x5.setText("7");
        cont++;
        jbtn3x5.setEnabled(false);
    }//GEN-LAST:event_jbtn3x5ActionPerformed

    private void jbtn3x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3x6ActionPerformed
        jbtn3x6.setText("8");
        cont++;
        jbtn3x6.setEnabled(false);
    }//GEN-LAST:event_jbtn3x6ActionPerformed

    private void jbtn3x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3x8ActionPerformed
        jbtn3x8.setText("1");
        cont++;
        jbtn3x8.setEnabled(false);
    }//GEN-LAST:event_jbtn3x8ActionPerformed

    private void jbtn4x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4x1ActionPerformed
        jbtn4x1.setText("2");
        cont++;
        jbtn4x1.setEnabled(false);
    }//GEN-LAST:event_jbtn4x1ActionPerformed

    private void jbtn4x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4x2ActionPerformed
        jbtn4x2.setText("3");
        cont++;
        jbtn4x2.setEnabled(false);
    }//GEN-LAST:event_jbtn4x2ActionPerformed

    private void jbtn4x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4x3ActionPerformed
        jbtn4x3.setText("4");
        cont++;
        jbtn4x3.setEnabled(false);
    }//GEN-LAST:event_jbtn4x3ActionPerformed

    private void jbtn4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4x4ActionPerformed
        jbtn4x4.setText("5");
        cont++;
        jbtn4x4.setEnabled(false);
    }//GEN-LAST:event_jbtn4x4ActionPerformed

    private void jbtn4x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4x7ActionPerformed
        jbtn4x7.setText("6");
        cont++;
        jbtn4x7.setEnabled(false);
    }//GEN-LAST:event_jbtn4x7ActionPerformed

    private void jbtn4x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4x8ActionPerformed
        jbtn4x8.setText("7");
        cont++;
        jbtn4x8.setEnabled(false);
    }//GEN-LAST:event_jbtn4x8ActionPerformed

    private void jbtn5x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5x2ActionPerformed
        jbtn5x2.setText("8");
        cont++;
        jbtn5x2.setEnabled(false);
    }//GEN-LAST:event_jbtn5x2ActionPerformed

    private void jbtn5x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5x3ActionPerformed
        jbtn5x3.setText("1");
        cont++;
        this.setEnabled(false);
    }//GEN-LAST:event_jbtn5x3ActionPerformed

    private void jbtn5x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5x5ActionPerformed
        jbtn5x5.setText("2");
        cont++;
        jbtn5x5.setEnabled(false);
    }//GEN-LAST:event_jbtn5x5ActionPerformed

    private void jbtn5x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5x6ActionPerformed
        jbtn5x6.setText("3");
        cont++;
        jbtn5x6.setEnabled(false);
    }//GEN-LAST:event_jbtn5x6ActionPerformed

    private void jbtn5x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5x7ActionPerformed
        jbtn5x7.setText("4");
        cont++;
        jbtn5x7.setEnabled(false);
    }//GEN-LAST:event_jbtn5x7ActionPerformed

    private void jbtn5x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5x8ActionPerformed
        jbtn5x8.setText("5");
        cont++;
        jbtn5x8.setEnabled(false);
    }//GEN-LAST:event_jbtn5x8ActionPerformed

    private void jbtn6x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6x1ActionPerformed
        jbtn6x1.setText("6");
        cont++;
        jbtn6x1.setEnabled(false);
    }//GEN-LAST:event_jbtn6x1ActionPerformed

    private void jbtn6x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6x2ActionPerformed
        jbtn6x2.setText("7");
        cont++;
        jbtn6x2.setEnabled(false);
    }//GEN-LAST:event_jbtn6x2ActionPerformed

    private void jbtn6x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6x3ActionPerformed
        jbtn6x3.setText("8");
        cont++;
        jbtn6x3.setEnabled(false);
    }//GEN-LAST:event_jbtn6x3ActionPerformed

    private void jbtn6x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6x4ActionPerformed
        jbtn6x4.setText("1");
        cont++;
        jbtn6x4.setEnabled(false);
    }//GEN-LAST:event_jbtn6x4ActionPerformed

    private void jbtn6x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6x5ActionPerformed
        jbtn6x5.setText("2");
        cont++;
        jbtn6x5.setEnabled(false);
    }//GEN-LAST:event_jbtn6x5ActionPerformed

    private void jbtn6x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6x7ActionPerformed
        jbtn6x7.setText("3");
        cont++;
        jbtn6x7.setEnabled(false);
    }//GEN-LAST:event_jbtn6x7ActionPerformed

    private void jbtn7x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7x1ActionPerformed
       jbtn7x1.setText("4");
        cont++;
        jbtn7x1.setEnabled(false);
    }//GEN-LAST:event_jbtn7x1ActionPerformed

    private void jbtn7x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7x3ActionPerformed
        jbtn7x3.setText("5");
        cont++;
        jbtn7x3.setEnabled(false);
    }//GEN-LAST:event_jbtn7x3ActionPerformed

    private void jbtn7x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7x4ActionPerformed
       jbtn7x4.setText("6");
        cont++;
        jbtn7x4.setEnabled(false);
    }//GEN-LAST:event_jbtn7x4ActionPerformed

    private void jbtn7x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7x5ActionPerformed
        jbtn7x5.setText("7");
        cont++;
        jbtn7x5.setEnabled(false);
    }//GEN-LAST:event_jbtn7x5ActionPerformed

    private void jbtn7x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7x6ActionPerformed
        jbtn7x6.setText("8");
        cont++;
        this.setEnabled(false);
    }//GEN-LAST:event_jbtn7x6ActionPerformed

    private void jbtn7x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7x7ActionPerformed
        jbtn7x7.setText("1");
        cont++;
        jbtn7x7.setEnabled(false);
    }//GEN-LAST:event_jbtn7x7ActionPerformed

    private void jbtn7x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7x8ActionPerformed
        jbtn7x8.setText("2");
        cont++;
        jbtn7x8.setEnabled(false);
    }//GEN-LAST:event_jbtn7x8ActionPerformed

    private void jbtn8x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8x1ActionPerformed
        jbtn8x1.setText("3");
        cont++;
        jbtn8x1.setEnabled(false);
    }//GEN-LAST:event_jbtn8x1ActionPerformed

    private void jbtn8x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8x2ActionPerformed
        jbtn8x2.setText("4");
        cont++;
        jbtn8x2.setEnabled(false);
    }//GEN-LAST:event_jbtn8x2ActionPerformed

    private void jbtn8x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8x3ActionPerformed
        jbtn8x3.setText("5");
        cont++;
        jbtn8x3.setEnabled(false);
    }//GEN-LAST:event_jbtn8x3ActionPerformed

    private void jbtn8x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8x4ActionPerformed
        jbtn8x4.setText("6");
        cont++;
        jbtn8x4.setEnabled(false);
    }//GEN-LAST:event_jbtn8x4ActionPerformed

    private void jbtn8x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8x5ActionPerformed
       jbtn8x5.setText("7");
        cont++;
        jbtn8x5.setEnabled(false);
    }//GEN-LAST:event_jbtn8x5ActionPerformed

    private void jbtn8x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8x7ActionPerformed
        jbtn8x7.setText("8");
        cont++;
        jbtn8x7.setEnabled(false);
    }//GEN-LAST:event_jbtn8x7ActionPerformed

    private void jbtn8x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8x8ActionPerformed
        jbtn8x8.setText("3");
        cont++;
        jbtn8x8.setEnabled(false);
    }//GEN-LAST:event_jbtn8x8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapaDoJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton34;
    private javax.swing.JToggleButton jToggleButton38;
    private javax.swing.JToggleButton jToggleButton50;
    private javax.swing.JToggleButton jToggleButton56;
    private javax.swing.JToggleButton jToggleButton62;
    private javax.swing.JToggleButton jToggleButton88;
    private javax.swing.JToggleButton jbtn1x1;
    private javax.swing.JToggleButton jbtn1x2;
    private javax.swing.JToggleButton jbtn1x3;
    private javax.swing.JToggleButton jbtn1x4;
    private javax.swing.JToggleButton jbtn1x5;
    private javax.swing.JToggleButton jbtn1x6;
    private javax.swing.JToggleButton jbtn1x7;
    private javax.swing.JToggleButton jbtn1x8;
    private javax.swing.JToggleButton jbtn2x1;
    private javax.swing.JToggleButton jbtn2x2;
    private javax.swing.JToggleButton jbtn2x3;
    private javax.swing.JToggleButton jbtn2x4;
    private javax.swing.JToggleButton jbtn2x5;
    private javax.swing.JToggleButton jbtn2x6;
    private javax.swing.JToggleButton jbtn2x7;
    private javax.swing.JToggleButton jbtn2x8;
    private javax.swing.JToggleButton jbtn3x1;
    private javax.swing.JToggleButton jbtn3x2;
    private javax.swing.JToggleButton jbtn3x3;
    private javax.swing.JToggleButton jbtn3x4;
    private javax.swing.JToggleButton jbtn3x5;
    private javax.swing.JToggleButton jbtn3x6;
    private javax.swing.JToggleButton jbtn3x7;
    private javax.swing.JToggleButton jbtn3x8;
    private javax.swing.JToggleButton jbtn4x1;
    private javax.swing.JToggleButton jbtn4x2;
    private javax.swing.JToggleButton jbtn4x3;
    private javax.swing.JToggleButton jbtn4x4;
    private javax.swing.JToggleButton jbtn4x5;
    private javax.swing.JToggleButton jbtn4x6;
    private javax.swing.JToggleButton jbtn4x7;
    private javax.swing.JToggleButton jbtn4x8;
    private javax.swing.JToggleButton jbtn5x1;
    private javax.swing.JToggleButton jbtn5x2;
    private javax.swing.JToggleButton jbtn5x3;
    private javax.swing.JToggleButton jbtn5x4;
    private javax.swing.JToggleButton jbtn5x5;
    private javax.swing.JToggleButton jbtn5x6;
    private javax.swing.JToggleButton jbtn5x7;
    private javax.swing.JToggleButton jbtn5x8;
    private javax.swing.JToggleButton jbtn6x1;
    private javax.swing.JToggleButton jbtn6x2;
    private javax.swing.JToggleButton jbtn6x3;
    private javax.swing.JToggleButton jbtn6x4;
    private javax.swing.JToggleButton jbtn6x5;
    private javax.swing.JToggleButton jbtn6x6;
    private javax.swing.JToggleButton jbtn6x7;
    private javax.swing.JToggleButton jbtn6x8;
    private javax.swing.JToggleButton jbtn7x1;
    private javax.swing.JToggleButton jbtn7x2;
    private javax.swing.JToggleButton jbtn7x3;
    private javax.swing.JToggleButton jbtn7x4;
    private javax.swing.JToggleButton jbtn7x5;
    private javax.swing.JToggleButton jbtn7x6;
    private javax.swing.JToggleButton jbtn7x7;
    private javax.swing.JToggleButton jbtn7x8;
    private javax.swing.JToggleButton jbtn8x1;
    private javax.swing.JToggleButton jbtn8x2;
    private javax.swing.JToggleButton jbtn8x3;
    private javax.swing.JToggleButton jbtn8x4;
    private javax.swing.JToggleButton jbtn8x5;
    private javax.swing.JToggleButton jbtn8x6;
    private javax.swing.JToggleButton jbtn8x7;
    private javax.swing.JToggleButton jbtn8x8;
    // End of variables declaration//GEN-END:variables
}
